server:
  port: 8080

spring:
  application:
    name: airfare-price-index
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/airfare_db
    username: whoisjson_user
    password: whoisjson_password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: whoisjson-airfare-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer